### PR TITLE
Updated dependencies and refactored to make work with newest version …

### PR DESCRIPTION
**Pull request by Tallestthomas**
…of node

### CODE REVIEW

**Comment by Tallestthomas** [comment]
I know this is an old project, I will gladly take over if you'd like. Its a small but useful thing for me.

**Comment by niftylettuce** [comment]
added you as an owner on NPM and also as collaborator here.

just published version v0.0.5 to npm

**Comment by Tallestthomas** [comment]
Awesome, glad to work on this 😄

**Comment by niftylettuce** [comment]
I believe it's broken on OS X atm, I got some node-gyp error when installing latest version of CLI locally

**Comment by Tallestthomas** [comment]
Which version macOS/Node are you using?
I'm on Sierra running node 9.7.1 and I'm not having any issues. Maybe post the error dump if you can?

**Pull request merged**
